In [3]:
import numpy as np
import pandas as pd

score=np.random.randint(50,101,size=(50,5))
score_df=pd.DataFrame(score,
             columns=['國文','英文','數學','地理','歷史'],
             index=range(1,51))
score_df.index.name='學號'
score_df.columns.name='科目'
sum_series=score_df.sum(axis=1)
mean_series=score_df.mean(axis=1)
sum_series.rank(method='min',ascending=False)
score_df

科目   國文  英文   數學   地理   歷史
學號
1    53  62   75   86   62
2    53  66   64   59   68
3    91  75   70   93   91
4    99  61   91   97   97
5    58  79   98   95   99
6    61  51   61   99   70
7    64  50   86  100   61
8    95  50   71   61   71
9    85  55   81   72   64
10   61  52   84   81   86
11   77  99   66   79   51
12   66  94   91   70  100
13   65  77   52   66   63
14   90  95   88   75   77
15   62  64   58   93   90
16   96  56   72   94   85
17   59  59   81   78   90
18   63  81   52   59   97
19   55  73   50   78   76
20   98  71   58   51   94
21   72  93   60   95   97
22   95  93   93   68   75
23   85  99   61   93   94
24   69  86   79   91   77
25   63  96  100   77   77
26   85  89   80   71  100
27   99  92   89   91   83
28   82  97   60   52   66
29   70  93   68   94   81
30   64  65   58   55   98
31   54  83   64   79   90
32  100  52   73   93   72
33   78  64   77   70   68
34   67  84   56   94   66
35  100  88   60   53   51
36   66  89   80   67   53
37   79  97   93   87   80
38   61  87   65   64   67
39   74  74   72   51   85
40   78  83   85   53   88
41   99  88   71   61   98
42   90  76   74   51   77
43   68  76   95   93   79
44   60  94   63   69   56
45   67  87   90   78   78
46   69  95   79   87   56
47   80  70   64   78   53
48   89  57   56   68   58
49   70  78   70   99   92
50   55  84   91   92   95

In [4]:
sum_series=score_df.sum(axis=1)
mean_series=score_df.mean(axis=1)
rank_series=sum_series.rank(method='min',ascending=False)
score_df['總分'] = sum_series
score_df['平均'] = mean_series
score_df['排名'] = rank_series
score_df

科目   國文  英文   數學   地理   歷史   總分    平均    排名
學號
1    53  62   75   86   62  338  67.6  46.0
2    53  66   64   59   68  310  62.0  50.0
3    91  75   70   93   91  420  84.0  10.0
4    99  61   91   97   97  445  89.0   2.0
5    58  79   98   95   99  429  85.8   5.0
6    61  51   61   99   70  342  68.4  43.0
7    64  50   86  100   61  361  72.2  32.0
8    95  50   71   61   71  348  69.6  40.0
9    85  55   81   72   64  357  71.4  33.0
10   61  52   84   81   86  364  72.8  31.0
11   77  99   66   79   51  372  74.4  24.0
12   66  94   91   70  100  421  84.2   9.0
13   65  77   52   66   63  323  64.6  49.0
14   90  95   88   75   77  425  85.0   6.0
15   62  64   58   93   90  367  73.4  28.0
16   96  56   72   94   85  403  80.6  18.0
17   59  59   81   78   90  367  73.4  28.0
18   63  81   52   59   97  352  70.4  38.0
19   55  73   50   78   76  332  66.4  47.0
20   98  71   58   51   94  372  74.4  24.0
21   72  93   60   95   97  417  83.4  11.0
22   95  93   93   68   75  424  84.8   8.0
23   85  99   61   93   94  432  86.4   4.0
24   69  86   79   91   77  402  80.4  19.0
25   63  96  100   77   77  413  82.6  14.0
26   85  89   80   71  100  425  85.0   6.0
27   99  92   89   91   83  454  90.8   1.0
28   82  97   60   52   66  357  71.4  33.0
29   70  93   68   94   81  406  81.2  17.0
30   64  65   58   55   98  340  68.0  45.0
31   54  83   64   79   90  370  74.0  26.0
32  100  52   73   93   72  390  78.0  21.0
33   78  64   77   70   68  357  71.4  33.0
34   67  84   56   94   66  367  73.4  28.0
35  100  88   60   53   51  352  70.4  38.0
36   66  89   80   67   53  355  71.0  37.0
37   79  97   93   87   80  436  87.2   3.0
38   61  87   65   64   67  344  68.8  42.0
39   74  74   72   51   85  356  71.2  36.0
40   78  83   85   53   88  387  77.4  22.0
41   99  88   71   61   98  417  83.4  11.0
42   90  76   74   51   77  368  73.6  27.0
43   68  76   95   93   79  411  82.2  15.0
44   60  94   63   69   56  342  68.4  43.0
45   67  87   90   78   78  400  80.0  20.0
46   69  95   79   87   56  386  77.2  23.0
47   80  70   64   78   53  345  69.0  41.0
48   89  57   56   68   58  328  65.6  48.0
49   70  78   70   99   92  409  81.8  16.0
50   55  84   91   92   95  417  83.4  11.0

In [ ]:
score_sorted_df = score_df.sort_values(by='排名',ascending=True)
score_sorted_df

In [12]:
#班上前5名
score_sorted_df.iloc[:5]

科目  國文  英文  數學  地理  歷史   總分    平均   排名
學號
27  99  92  89  91  83  454  90.8  1.0
4   99  61  91  97  97  445  89.0  2.0
37  79  97  93  87  80  436  87.2  3.0
23  85  99  61  93  94  432  86.4  4.0
5   58  79  98  95  99  429  85.8  5.0

In [14]:
#班上後5名
score_sorted_df.iloc[-5:]

科目  國文  英文  數學  地理  歷史   總分    平均    排名
學號
1   53  62  75  86  62  338  67.6  46.0
19  55  73  50  78  76  332  66.4  47.0
48  89  57  56  68  58  328  65.6  48.0
13  65  77  52  66  63  323  64.6  49.0
2   53  66  64  59  68  310  62.0  50.0